services:
  laravel:
    build: laravel
    ports:
      - "8000:8000"
    volumes:
      - ${LARAVEL_PATH}:/var/www/laravel
  mysql:
    build: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: